version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     working_directory: ~/react-cafe-cms
     steps:
       - checkout
       - run:
           name: Install pcakage
           command: yarn install
       - save_cache:
           key: dependency-cache-{{ checksum "package.json" }}
           paths:
             - ~/react-cafe-cms

   test:
      docker:
        - image: circleci/node:latest
      working_directory: ~/react-cafe-cms
      steps:
        - checkout
        - restore_cache:
            keys:
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
              - dependency-cache-{{ checksum "package.json" }}
        - run:
            name: Test
            command: yarn test
        - run:
            name: Save test results
            command: |
              npm install --global ava
              yarn add ava tap-xunit --dev
              mkdir -p ~/reports
              ava --tap | tap-xunit > /reports/ava.xml
            when: always
        - store_test_results:
            path: ~/reports
        - store_artifacts:
            path: ~/reports


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
