version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run:
           name: Install npm pcakage
           command: npm install
       - save_cache:
           key: dependency-cache-{{ checksum "package.json" }}
           paths: - node_modules

   test:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Test
            command: yarn test
        - store_test_results:
            path: /tmp/test-results


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
